name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Login to Container Registry
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Build Containers
      #   run: |
      #     docker build -t witnet/witty-creatures-ui:latest -f ./ansible/docker/ui.dockerfile .
      #     docker build -t witnet/witty-creatures-api:latest -f ./ansible/docker/api.dockerfile .

      # - name: Publish Containers
      #   run: |
      #     docker push witnet/witty-creatures-ui:latest
      #     docker push witnet/witty-creatures-api:latest      

      - name: Create Deployment Files
        shell: bash
        env: 
          ENVARS: ${{ secrets.ENVIRONMENT_VARIABLES }}
        run: |
          echo "$ENVARS" > ./packages/ui/.env
          echo "$ENVARS" > ./packages/api/.env
          echo "$ENVARS" > ./ansible/.env
          echo ${{ secrets.ANSIBLE_INVENTORY }} > ./ansible/inventory.ini
          echo ${{ secrets.ANSIBLE_PRIVATE_KEY }} > ./ansible/key.pem
          chmod 400 ./ansible/key.pem
          
      
      - name: Deploy with Ansible
        shell: bash
        run: |
          cd ansible
          export ANSIBLE_CONFIG=./ansible.cfg
          export ANSIBLE_FORCE_COLOR=True
          export ANSIBLE_STDOUT_CALLBACK=yaml
          export FORCE_COLOR=1
          export TERM=xterm-color
          ansible-playbook ./helpers/docker-playbook.yml -vv
          ansible-playbook playbook.yml -vv
